src/Entity/Opposition.php
<?php

namespace App\Entity;

use App\Repository\OppositionRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OppositionRepository::class)]
class Opposition
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(nullable: true)]
    private ?int $score_equipe1 = null;

    #[ORM\Column(nullable: true)]
    private ?int $score_equipe2 = null;

    #[ORM\ManyToOne(inversedBy: 'oppositions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Equipe $equipe1 = null;

    #[ORM\ManyToOne(inversedBy: 'oppositions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Equipe $equipe2 = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getScoreEquipe1(): ?int
    {
        return $this->score_equipe1;
    }

    public function setScoreEquipe1(?int $score_equipe1): static
    {
        $this->score_equipe1 = $score_equipe1;

        return $this;
    }

    public function getScoreEquipe2(): ?int
    {
        return $this->score_equipe2;
    }

    public function setScoreEquipe2(?int $score_equipe2): static
    {
        $this->score_equipe2 = $score_equipe2;

        return $this;
    }

    public function getEquipe1(): ?Equipe
    {
        return $this->equipe1;
    }

    public function setEquipe1(?Equipe $equipe1): static
    {
        $this->equipe1 = $equipe1;

        return $this;
    }

    public function getEquipe2(): ?Equipe
    {
        return $this->equipe2;
    }

    public function setEquipe2(?Equipe $equipe2): static
    {
        $this->equipe2 = $equipe2;

        return $this;
    }


}

src/Controller/HomePageController.php
<?php

namespace App\Controller;

use App\Controller\EquipeController;
use App\Repository\EquipeRepository;
use App\Repository\ArticleRepository;
use App\Repository\OppositionRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class HomePageController extends AbstractController
{


    #[Route('/', name: 'app_home_page')]
    public function index(OppositionRepository $oppositionRepository, EquipeRepository $equipeRepository, ArticleRepository $articleRepository): Response
    {
        
        // / Appel de la méthode lastMatchSixFours pour récupérer le dernier match de Six-Fours et les affichers à la vue
        $lastMatchSixFours = $oppositionRepository->lastMatchSixFours();
        
        // Récupérer les résultats des matchs pour chaque équipe
        $resultsByEquipe = [];
        $equipes = $equipeRepository->findAll();
        foreach ($equipes as $equipe) {
            $resultsByEquipe[$equipe->getId()] = $oppositionRepository->getOppositionByEquipe($equipe->getId());
        }
        
        

        return $this->render('home_page/index.html.twig', [
            'controller_name' => 'HomePageController',
            'lastMatchSixFours' => $lastMatchSixFours,
            'equipes' => $equipeRepository->findAll(),

            
            
            'articles' => $articleRepository->findAll(),
            // 'articles' => $articleRepository->findBy(array('rubrique_id' => 1)),
        ]);
    }

  
}

templates/home_page/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomePageController!{% endblock %}

{% block body %}

<main>
    <div class="cont-main">

        {# BLOC ACTUALITE CARROUSSEL------------------------------------------------- #}
        {# -------------------------------------------------------------------------- #}
        <section class="cont-articles">
            <div class="item">
                <div class="title-articles">
                    <h2>Titre article rubrique actualité</h2>
                    <p>Bref description de l'article</p>
                    <button class="btn-index" href="#">Lire</button>
                </div>
            </div>
        </section>

        {# BLOC RECUPERATION DONNEES MATCHS ET CLASSEMENT------------------------------- #}
        {#-----------------------------------------------------------------------------  #}
        <section class="cont-match-classement">
            <div class="box-match-classement">
                <h3> Matchs </h3>

                {# recupere le dernier match de l'equipe de six-fours avec date et logo des deux equipes #}
                {% if lastMatchSixFours %}
                <div class="date-match">
                    <p>{{ lastMatchSixFours.date |date('d-m-Y') }}</p>
                </div>
                <div class="logo-match">
                    <img src="{{ '/images/logo/' ~ lastMatchSixFours.equipe1.imageName }}">
                    <img src="{{ '/images/logo/' ~ lastMatchSixFours.equipe2.imageName }}">
                </div>
                <div class="box-score-class">
                    <div class="equipe-score-match">
                        <p>{{ lastMatchSixFours.equipe1.nom }} <span class="versus">vs</span> {{ lastMatchSixFours.equipe2.nom }}</p>
                        <p>{{ lastMatchSixFours.scoreEquipe1 }} - {{ lastMatchSixFours.scoreEquipe2 }}</p>
                        <div class="all-matchs">
                            <a href="{{path('app_opposition_index')}}"> Voir tous les matchs </a>
                        </div>
                    </div>
                    {% else %}
                        <p>Aucun match trouvé.</p>
                    {% endif %}


                    {# récupère les 4 premier equipes du classement avec points match joue ect #}
                    <div class="classement-match">
                        <p> Classement</p>
                        {# {{ dump(scores) }} #}
                        {% for equipe in equipes|slice(0, 4) %}
                            <div class="stat-match">
                                <div class="nom-equipe">
                                    <p>{{ equipe.nom }}</p>                         
                                </div>


                                {# <p>{{ scores[equipe.id] }}</p>  #}
                                {# <p>{{ matches[equipe.id] }}</p>
                                <p>{{ matchesGagne[equipe.id] }}</p>
                                <p>{{ matchesNul[equipe.id] }}</p>
                                <p>{{ matchesPerdu[equipe.id] }}</p> #}
                            </div>   
                        {% endfor %}
                        <a href="{{path('app_equipe_index')}}"> Voir tous le classement </a>  
                    </div>  
                </div>              
            </div>   
        </section>

        {# BLOC ACTUALITE--------------------------------------------------------------- #}
        {#-----------------------------------------------------------------------------  #}
        <section class="cont-actualite">
            <h2 class="actualite-title"> ACTUALITE </h2>

            {# actu  #}
            {% for article in articles  %}
                <article class="box-actualite">
                    <div  class="img-section-actualite">
                        <img src="/images/{{ article.image }}"
                    </div>                    
                    <div class="box-title">
                        <h2>{{ article.titre }}</h2>  
                    </div>
                </article>
            {% endfor %}
        </section>

       
        {# BLOC EVENEMENT--------------------------------------------------------------- #}
        {# ----------------------------------------------------------------------------- #}

        <section class="cont-evenement">
            <h2 class"evenement-title"> EVENEMENT </h2>

            {# event #}
            {% for articles in articles %}
                <article class="box-evenement">
                    <div class="img-section-evenement">
                        {# <img src="/images/{{ article.image }}" #}
                        <img src="/images/evenement_4.jpg" alt="victoire celebration">
                    </div>
                    <div class="box-title-evenement">
                        <h2>Titre event</h2>
                    </div>
                </article>
            {% endfor %}
        </section>
        
        
        
        
        
        
        
        
        
        {# <section class="cont-evenement">
            <div class="evenement-title">
                <h2> EVENEMENT </h2>
            </div> 

            {# evenement 1 #}
            {# <div class="box-evenement box-evenement1">
                <div class="img-event img-event-1">
                    <img src="/images/evenement_4.jpg" alt="victoire celebration">  
                </div>
                <div class="box-title-evenement">  
                    <h3> Titre de l'évènement 1 </h3>  
                </div>   
            </div> #}

            {# evenement 2 #}
            {# <div class="cont-event2-event3">
                <div class="box-evenement box-evenement2">
                    <div class="img-event img-event-2">
                        <img src="/images/evenement_1.jpg" alt="stade avec joueurs">  
                    </div>
                    <div class="box-title-evenement">
                        <h3> Titre de l'évènement 2 </h3>  
                    </div>   
                </div> #}

                {# evenement 3 #}
                {# <div class="box-evenement box-evenement3">
                    <div class="img-event img-event-3">
                        <img src="/images/evenement_2.jpg" alt="joueurs à l'entrainement">  
                    </div>
                    <div class="box-title-evenement">
                        <h3> Titre de l'évènement 3 </h3>  
                    </div> 
                </div>
            </div> #}

            {# evenement 4 #}
            {# <div class="box-evenement box-evenement4">
                <div class="img-event img-event-4">
                    <img src="/images/evenement_6.jpg" alt="joueurs à l'entrainement">  
                </div>
                <div class="box-title-evenement">
                     <h3> Titre de l'évènement 4 </h3>  
                </div> 
            </div> #}

            {# evenement 5 #}
            {# <div class="box-evenement box-evenement5">
                <div class="img-event img-event-5">
                    <img src="/images/evenement_5.avif" alt="joueurs à l'entrainement">  
                </div>
                <div class="box-title-evenement">
                     <h3> Titre de l'évènement 5 </h3>  
                </div> 
            </div> #}
        {# </section>  #}
            
        {# BLOC BOUTIQUE---------------------------------------------------------------- #}
        {# ------------------------------------------------------------------------------#}
        <section class="cont-shop">
            <div class="shop-titre">
                <h2> BOUTIQUE </h2>
            </div> 

            {# shop 1 #}
            <div class="cont-box-shop">
                <div class="box-shop box-shop1">
                    <div class="img-shop img-shop-1">
                        <img src="/images/shop1.jpg" alt="ensemble maillot short">  
                    </div>
                    <div class="box-bouton">  
                        <button class="btn-shop" type="submit">ACHAT</button> 
                    </div>   
                </div>

                {# shop 2 #}
                <div class="box-shop box-shop2">
                    <div class="img-shop img-shop-2">
                        <img src="/images/shop2.jpg" alt="ensemble maillot short">  
                    </div>
                    <div class="box-bouton">  
                        <button class="btn-shop" type="submit">ACHAT</button> 
                    </div>   
                </div>

                {# shop 3 #}
                <div class="box-shop box-shop3">
                    <div class="img-shop img-shop-3">
                        <img src="/images/shop3.jpg" alt="ensemble maillot short">  
                    </div>
                    <div class="box-bouton"> 
                        <button class="btn-shop" type="submit">ACHAT</button>  
                    </div>   
                </div>
            </div>
        </div>

        {# EQUIPE 1ER LIEN VERS JOUEURS------------------------------------------------- #}
        {# ----------------------------------------------------------------------------- #}
        <div class="cont-equipe1">
            <div class="overley-joueur">
                <div class="title-image">
                      <h2> EQUIPE PREMIERE </h2> 
                    <div class="para-image">
                         <p> COMPOSITION </p>
                    </div>
                    <button class="btn-index" type="submit">LIRE</button>
                </div>
            </div>
        </div>


        {# BLOC PARTENAIRES----------------------------------------------------------- #}
        {# ----------------------------------------------------------------------------- #}
        <div class="cont-partenaire">
            <div class="box-partenaire">
                <div class="titre-partenaires">
                    <h2>PARTENAIRES</h2>
                </div>
                <div class="logo-partenaire">
                    <img src="/images/Six-Fours-les-Plages.png" alt="logo ville de six fours">
                    <img src="/images/Kappa-Logo.png" alt="logo kappa">
                    <img src="/images/district.png" alt="logo district du var">
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock %}