src/Entity/Joueur.php
<?php

namespace App\Entity;

use Vich\UploadableField;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\JoueurRepository;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


#[ORM\Entity(repositoryClass: JoueurRepository::class)]
#[Vich\Uploadable]
class Joueur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_naissance = null;

    #[ORM\Column]
    private ?int $numero = null;

    #[ORM\Column(length: 255)]
    private ?string $poste = null;

    #[ORM\Column(nullable: true)]
    private ?int $numero_licence = null;

    #[ORM\Column]
    private ?int $cartonJaune = null;

    #[ORM\Column]
    private ?int $cartonRouge = null;

    #[ORM\Column]
    private ?int $matchJoue = null;

    #[ORM\Column(nullable: true)]
    private ?int $nbrPasse = null;

    #[ORM\Column(nullable: true)]
    private ?int $nbrPasseDecisif = null;

    #[ORM\Column(nullable: true)]
    private ?int $nbrTir = null;

    #[ORM\Column(nullable: true)]
    private ?int $nbrBut = null;

    #[ORM\Column(nullable: true)]
    private ?int $arretGardien = null;

    #[ORM\Column(nullable: true)]
    private ?int $butEncaisser = null;

    #[ORM\Column(nullable: true)]
    private ?int $penaltyDispute = null;

    #[ORM\Column(nullable: true)]
    private ?int $penaltyArrete = null;

    #[ORM\ManyToOne(inversedBy: 'joueurs')]
    private ?Equipe $equipe = null;

    #[ORM\Column(length: 255)]
    private ?string $joueur_image_name = null;



   
    #[Vich\UploadableField(mapping: 'logo_images', fileNameProperty: 'joueurImageName')]
    private ?File $imageFile = null;

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

    }





    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): static
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getNumero(): ?int
    {
        return $this->numero;
    }

    public function setNumero(int $numero): static
    {
        $this->numero = $numero;

        return $this;
    }

    public function getPoste(): ?string
    {
        return $this->poste;
    }

    public function setPoste(string $poste): static
    {
        $this->poste = $poste;

        return $this;
    }

    public function getNumeroLicence(): ?int
    {
        return $this->numero_licence;
    }

    public function setNumeroLicence(?int $numero_licence): static
    {
        $this->numero_licence = $numero_licence;

        return $this;
    }

    public function getCartonJaune(): ?int
    {
        return $this->cartonJaune;
    }

    public function setCartonJaune(int $cartonJaune): static
    {
        $this->cartonJaune = $cartonJaune;

        return $this;
    }

    public function getCartonRouge(): ?int
    {
        return $this->cartonRouge;
    }

    public function setCartonRouge(int $cartonRouge): static
    {
        $this->cartonRouge = $cartonRouge;

        return $this;
    }

    public function getMatchJoue(): ?int
    {
        return $this->matchJoue;
    }

    public function setMatchJoue(int $matchJoue): static
    {
        $this->matchJoue = $matchJoue;

        return $this;
    }

    public function getNbrPasse(): ?int
    {
        return $this->nbrPasse;
    }

    public function setNbrPasse(?int $nbrPasse): static
    {
        $this->nbrPasse = $nbrPasse;

        return $this;
    }

    public function getNbrPasseDecisif(): ?int
    {
        return $this->nbrPasseDecisif;
    }

    public function setNbrPasseDecisif(?int $nbrPasseDecisif): static
    {
        $this->nbrPasseDecisif = $nbrPasseDecisif;

        return $this;
    }

    public function getNbrTir(): ?int
    {
        return $this->nbrTir;
    }

    public function setNbrTir(?int $nbrTir): static
    {
        $this->nbrTir = $nbrTir;

        return $this;
    }

    public function getNbrBut(): ?int
    {
        return $this->nbrBut;
    }

    public function setNbrBut(?int $nbrBut): static
    {
        $this->nbrBut = $nbrBut;

        return $this;
    }

    public function getArretGardien(): ?int
    {
        return $this->arretGardien;
    }

    public function setArretGardien(?int $arretGardien): static
    {
        $this->arretGardien = $arretGardien;

        return $this;
    }

    public function getButEncaisser(): ?int
    {
        return $this->butEncaisser;
    }

    public function setButEncaisser(?int $butEncaisser): static
    {
        $this->butEncaisser = $butEncaisser;

        return $this;
    }

    public function getPenaltyDispute(): ?int
    {
        return $this->penaltyDispute;
    }

    public function setPenaltyDispute(?int $penaltyDispute): static
    {
        $this->penaltyDispute = $penaltyDispute;

        return $this;
    }

    public function getPenaltyArrete(): ?int
    {
        return $this->penaltyArrete;
    }

    public function setPenaltyArrete(?int $penaltyArrete): static
    {
        $this->penaltyArrete = $penaltyArrete;

        return $this;
    }

    public function getEquipe(): ?Equipe
    {
        return $this->equipe;
    }

    public function setEquipe(?Equipe $equipe): static
    {
        $this->equipe = $equipe;

        return $this;
    }

    public function getJoueurImageName(): ?string
    {
        return $this->joueur_image_name;
    }

    public function setJoueurImageName(string $joueur_image_name): static
    {
        $this->joueur_image_name = $joueur_image_name;

        return $this;
    }

 





}

src/Form/JoueurType.php
<?php

namespace App\Form;

use App\Entity\Equipe;
use App\Entity\Joueur;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class JoueurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('date_naissance', null, [
                'widget' => 'single_text',
            ])
            ->add('numero')
            ->add('poste', ChoiceType::class,[
                'choices' => [
                    'Attaquants' => 'Attaquant',
                    'Milieux' => 'Milieux',
                    'Défenseurs' => 'Défenseurs',
                    'Gardiens' => 'Gardien',
                ],
            ])
            ->add('numero_licence')
            ->add('cartonJaune')
            ->add('cartonRouge')
            ->add('matchJoue')
            ->add('nbrPasse')
            ->add('nbrPasseDecisif')
            ->add('nbrTir')
            ->add('nbrBut')
            ->add('arretGardien')
            ->add('butEncaisser')
            ->add('penaltyDispute')
            ->add('penaltyArrete')
            ->add('equipe', EntityType::class, [
                'class' => Equipe::class,
                'choice_label' => 'nom',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Joueur::class,
        ]);
    }
}

src/Controller/JoueurController.php
<?php

namespace App\Controller;

use App\Entity\Joueur;
use App\Form\JoueurType;
use App\Repository\JoueurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/joueur')]
class JoueurController extends AbstractController
{
    #[Route('/', name: 'app_joueur_index', methods: ['GET'])]
    public function index(JoueurRepository $joueurRepository): Response
    {
        return $this->render('joueur/index.html.twig', [
            'joueurs' => $joueurRepository->findAll(),
        ]);
    }

    // methode qui definie l'affichage des cartes joueurs
    #[Route('/cards', name: 'app_joueur_cards', methods: ['GET'])]
    public function showCards(JoueurRepository $joueurRepository): Response
    {
        $joueurs = $joueurRepository->findAll();

        return $this->render('joueur/cards.html.twig', [
            'joueurs' => $joueurs,
        ]);
    }

    // methode qui permet de recuperer les stat individuel des joueurs
    #[Route('/stat/{id}', name: 'app_joueur_stat', methods: ['GET'])]
    public function statistiqueJoueur(int $id, JoueurRepository $joueurRepository): Response
    {
        $joueur = $joueurRepository->find($id);

        return $this->render('joueur/stat.html.twig', [
            'joueur' => $joueur,
        ]);
    }



    #[Route('/new', name: 'app_joueur_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $joueur = new Joueur();
        $form = $this->createForm(JoueurType::class, $joueur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($joueur);
            $entityManager->flush();

            return $this->redirectToRoute('app_joueur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('joueur/new.html.twig', [
            'joueur' => $joueur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_joueur_show', methods: ['GET'])]
    public function show(Joueur $joueur): Response
    {
        return $this->render('joueur/show.html.twig', [
            'joueur' => $joueur,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_joueur_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Joueur $joueur, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(JoueurType::class, $joueur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_joueur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('joueur/edit.html.twig', [
            'joueur' => $joueur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_joueur_delete', methods: ['POST'])]
    public function delete(Request $request, Joueur $joueur, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$joueur->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($joueur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_joueur_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/joueur/cards.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Joueurs{% endblock %}

{% block body %}

    <div class="container">
        <h1>Liste des Joueurs</h1>
        <div class="row">
            {% for joueur in joueurs %}
                <div class="col-md-4">
                    <div class="card">
                        {# <img src="../images/card.jpg" class="card-img-top" alt="profil joueur"> #}
                        <img src="{{ vich_uploader_asset(joueur, 'imageFile') }}">
                        <div class="card-title">
                            {{ joueur.nom }} {{ joueur.prenom }}
                        </div>
                        <div class="card-content">
                            <p>{{ joueur.numero }}</p>
                            <p>{{ joueur.poste }}</p>
                            <!-- Ajoutez d'autres informations du joueur ici -->
                            <a href="{{path('app_joueur_stat', {'id': joueur.id})}}" class="btn btn-danger mt-4 mb-4">Statistique</a>

{# 
                            <a href="{{ path('app_joueur_show', {'id': joueur.id}) }}" class="btn btn-primary mt-2">Voir</a>
                            <a href="{{ path('app_joueur_edit', {'id': joueur.id}) }}" class="btn btn-warning mt-2">Modifier</a>
                            <form method="post" action="{{ path('app_joueur_delete', {'id': joueur.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce joueur ?');" class="mt-2">
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ joueur.id) }}">
                                <button class="btn btn-danger">Supprimer</button>
                            </form> #}
                            {% if is_granted('ROLE_ADMIN') %}
                                <a href="{{ path('app_joueur_edit', {'id': joueur.id}) }}" class="btn btn-warning mt-2">Modifier</a>
                                <a href="{{ path('app_joueur_show', {'id': joueur.id}) }}" class="btn btn-info mt-2">Afficher</a>
                                <a href="{{ path('app_joueur_new') }}" class="btn btn-success mt-2">Ajouter</a>
                                <form action="{{ path('app_joueur_delete', {'id': joueur.id}) }}" method="post" style="display: inline;">
                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ joueur.id) }}">
                                    <button type="submit" class="btn btn-primary mt-2">Supprimer</button>
                                </form>
                            {% endif %}

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/joueur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Joueur index{% endblock %}

{% block body %}

    <main>
        <section class="container">
            <h1>Joueur index</h1>

            <table class="table">
                <thead>
                    <tr>
                        {# <th>Id</th> #}
                        <th>Nom</th>
                        <th>Prenom</th>
                        <th>Date_naissance</th>
                        <th>Numero</th>
                        <th>Poste</th>
                        <th>Numero_licence</th>
                        <th>CartonJaune</th>
                        <th>CartonRouge</th>
                        <th>MatchJoue</th>
                        <th>NbrPasse</th>
                        <th>NbrPasseDecisif</th>
                        <th>NbrTir</th>
                        <th>NbrBut</th>
                        <th>ArretGardien</th>
                        <th>ButEncaisser</th>
                        <th>PenaltyDispute</th>
                        <th>PenaltyArrete</th>
                        <th>actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for joueur in joueurs %}
                    <tr>
                        {# <td>{{ joueur.id }}</td> #}
                        <td>{{ joueur.nom }}</td>
                        <td>{{ joueur.prenom }}</td>
                        <td>{{ joueur.dateNaissance ? joueur.dateNaissance|date('Y-m-d') : '' }}</td>
                        <td>{{ joueur.numero }}</td>
                        <td>{{ joueur.poste }}</td>
                        <td>{{ joueur.numeroLicence }}</td>
                        <td>{{ joueur.cartonJaune }}</td>
                        <td>{{ joueur.cartonRouge }}</td>
                        <td>{{ joueur.matchJoue }}</td>
                        <td>{{ joueur.nbrPasse }}</td>
                        <td>{{ joueur.nbrPasseDecisif }}</td>
                        <td>{{ joueur.nbrTir }}</td>
                        <td>{{ joueur.nbrBut }}</td>
                        <td>{{ joueur.arretGardien }}</td>
                        <td>{{ joueur.butEncaisser }}</td>
                        <td>{{ joueur.penaltyDispute }}</td>
                        <td>{{ joueur.penaltyArrete }}</td>
                        <td>
                            <a href="{{ path('app_joueur_show', {'id': joueur.id}) }}">show</a>
                            <a href="{{ path('app_joueur_edit', {'id': joueur.id}) }}">edit</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="19">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <a href="{{ path('app_joueur_new') }}">Create new</a>
        </section>
    </main>

{% endblock %}

templates/joueur/stat.html.twig
{% extends 'base.html.twig' %}

{% block title %}Statistiques du joueur {% endblock %}

{% block body %}
    <div class="container">
        <div class="profil-img">
            <img src="{{ vich_uploader_asset(joueur, 'imageFile') }}">
            {{ joueur.nom }} {{ joueur.prenom }}
        </div>
        <div class="box-stat">
            <div class="poste">
                <p>{{ joueur.poste }}</p>
            </div>

            <div class="match">
                <p> matchs joués</p>
                <p>{{ joueur.matchJoue }}</p>
            </div>

            <div class="carton">
                <p>{{ joueur.cartonJaune }} Carton jaune</p>
                <p>{{ joueur.cartonRouge }} Carton rouge</p>
            </div>

            <div class="passe">
                <p>{{ joueur.nbrPasse }} Passes</p>
                <p>{{ joueur.nbrPasseDecisif }} Passes décisifs</p>
            </div>

            <div class="tir">
                <p>{{ joueur.nbrTir }} Tir</p>
                <p>{{ joueur.nbrBut }} But</p>
            </div>

            {% if joueur.poste == 'Gardien de but' %}   {#condition pour que les statistiques gardiens apparaissent que pour le poste gardien de but#}
            <div class="gardien">
                <div class="arret-but">
                    <p>{{ joueur.arretGardien }} Arret gardien</p>
                    <p>{{ joueur.butEncaisser }} But encaissé</p>
                </div>
                <div class="penalty">
                    <p>{{ joueur.penaltyDispute }} Penalty dispute</p>
                    <p>{{ joueur.penaltyArrete }} Penalty arrete</p>
                </div>
            </div>
            {% endif %}
        </div>
        <a href="{{path('app_joueur_cards')}}" class="btn btn-stat btn-danger mt-4 mb-4"> Retour </a> 
    </div>

   
{% endblock %}